

import java.sql.*;
import javax.swing.JOptionPane;
import java.awt.*;
import java.awt.event.*;
import net.proteanit.sql.DbUtils;
/**
 *
 * @author Alphacoders
 */
public class Record_Details extends javax.swing.JFrame {

    
    
    /**
     * Creates new form Record_Details
     */
    public Record_Details() {
        initComponents();
  
        lC.setVisible(false);
        lD.setVisible(false);
        locLab.setVisible(false);
        lN.setVisible(false);
        lS.setVisible(false);
        lC.setVisible(false);

        tname.setVisible(false);
        tLocation.setVisible(false);
        tDate.setVisible(false);
        tTime.setVisible(false);

        tContact.setVisible(false);
        btn_Search.setVisible(false);

        jScrollPane1.setVisible(false);
        
        
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        lN = new javax.swing.JLabel();
        lD = new javax.swing.JLabel();
        lS = new javax.swing.JLabel();
        lC = new javax.swing.JLabel();
        tname = new javax.swing.JTextField();
        tDate = new javax.swing.JTextField();
        tTime = new javax.swing.JTextField();
        tContact = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        btn_Search = new javax.swing.JButton();
        locLab = new javax.swing.JLabel();
        tLocation = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        empTable = new javax.swing.JTable();
        radListAll = new javax.swing.JRadioButton();
        radSearch = new javax.swing.JRadioButton();
        btn_Next = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Details Window");

        jPanel1.setLayout(null);

        lN.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lN.setForeground(new java.awt.Color(153, 0, 153));
        lN.setText("NAME");
        jPanel1.add(lN);
        lN.setBounds(30, 160, 100, 30);

        lD.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lD.setForeground(new java.awt.Color(153, 0, 153));
        lD.setText("Date");
        jPanel1.add(lD);
        lD.setBounds(30, 380, 210, 30);

        lS.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lS.setForeground(new java.awt.Color(153, 0, 153));
        lS.setText("Time");
        jPanel1.add(lS);
        lS.setBounds(20, 510, 180, 30);

        lC.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lC.setForeground(new java.awt.Color(153, 0, 153));
        lC.setText("Contact");
        jPanel1.add(lC);
        lC.setBounds(20, 620, 200, 30);

        tname.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        tname.setForeground(new java.awt.Color(255, 51, 102));
        jPanel1.add(tname);
        tname.setBounds(270, 150, 360, 50);

        tDate.setEditable(false);
        tDate.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        tDate.setForeground(new java.awt.Color(255, 51, 51));
        jPanel1.add(tDate);
        tDate.setBounds(270, 380, 360, 50);

        tTime.setEditable(false);
        tTime.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        tTime.setForeground(new java.awt.Color(255, 51, 51));
        jPanel1.add(tTime);
        tTime.setBounds(270, 490, 360, 50);

        tContact.setEditable(false);
        tContact.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        tContact.setForeground(new java.awt.Color(255, 51, 51));
        jPanel1.add(tContact);
        tContact.setBounds(270, 610, 360, 50);

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 102, 102));
        jButton1.setText("RETURN");
        jButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(1140, 570, 150, 50);

        btn_Search.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btn_Search.setForeground(new java.awt.Color(255, 0, 0));
        btn_Search.setText("SEARCH");
        btn_Search.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        btn_Search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SearchActionPerformed(evt);
            }
        });
        jPanel1.add(btn_Search);
        btn_Search.setBounds(670, 160, 190, 50);

        locLab.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        locLab.setForeground(new java.awt.Color(153, 0, 153));
        locLab.setText("Location");
        jPanel1.add(locLab);
        locLab.setBounds(20, 260, 180, 50);

        tLocation.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        tLocation.setForeground(new java.awt.Color(255, 51, 51));
        jPanel1.add(tLocation);
        tLocation.setBounds(270, 260, 360, 50);

        empTable.setBackground(new java.awt.Color(204, 0, 102));
        empTable.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        empTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Name", "Location", "Date", "Time", "Contact"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(empTable);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(20, 210, 1120, 580);

        buttonGroup1.add(radListAll);
        radListAll.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        radListAll.setForeground(new java.awt.Color(255, 0, 0));
        radListAll.setText("List All Records");
        jPanel1.add(radListAll);
        radListAll.setBounds(30, 20, 400, 40);

        buttonGroup1.add(radSearch);
        radSearch.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        radSearch.setForeground(new java.awt.Color(255, 0, 0));
        radSearch.setText("Search");
        jPanel1.add(radSearch);
        radSearch.setBounds(30, 70, 300, 40);

        btn_Next.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        btn_Next.setForeground(new java.awt.Color(102, 102, 102));
        btn_Next.setText("NEXT");
        btn_Next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_NextActionPerformed(evt);
            }
        });
        jPanel1.add(btn_Next);
        btn_Next.setBounds(440, 70, 180, 40);

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 102, 102));
        jButton2.setText("CLEAR");
        jButton2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(1140, 670, 150, 50);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/stark/industries/Background.jpg"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(0, 0, 1300, 810);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1293, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 801, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
       Statement stmt = null;
     ResultSet rs = null;
     
     public static Connection getConnection(){
         Connection con=null;
         try{
             Class.forName("com.mysql.jdbc.Driver");
             con=DriverManager.getConnection("jdbc:mysql://localhost:3306/shop","root","stid");
         }
         catch (Exception ex){
             JOptionPane.showMessageDialog(null, "Connection Failure");
         }
         
         return con;
     }
     
     
    private void btn_SearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SearchActionPerformed
        // TODO add your handling code here:
        
        lC.setVisible(true);
        lD.setVisible(true);
        locLab.setVisible(true);
        lN.setVisible(true);
        lS.setVisible(true);
        lC.setVisible(true);
        tname.setVisible(true);
        tLocation.setVisible(true);
        tDate.setVisible(true);
        tTime.setVisible(true);
        tContact.setVisible(true);
        
        
       
        
        
        String name=tname.getText();
        String loc = tLocation.getText();
       Statement pstmt;
        pstmt = null;
       Connection conn=null;
       ResultSet rs = null;
       try{
           Class.forName("com.mysql.jdbc.Driver");
           conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/shop","root","stid");
           stmt=conn.createStatement();
           rs=stmt.executeQuery("select * from Customers where Name="+"'"+name+"'"+"&& Location="+"'"+loc+"'"+";");
           
           while(rs.next()){
               tname.setText(rs.getString(1));
               tDate.setText(rs.getString(3));
               tTime.setText(rs.getString(4));
               tContact.setText(rs.getString(5));
               tLocation.setText(rs.getString(2));
               

              
           }
       }
       catch(Exception ex){
           JOptionPane.showMessageDialog(null, ex.toString());
       }
       finally{
        try{
            conn.close();
            pstmt.close();
            rs.close();
        }
        catch(Exception ex){
           
        }
        
        }
       
      
        
      
    }//GEN-LAST:event_btn_SearchActionPerformed

    public void close(){
        WindowEvent winClosingEvent = new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
         Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);
    }
    
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Exiting Search Window...");
        Welcome_Screen gy = new Welcome_Screen();
        gy.setVisible(true);
        close();
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btn_NextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_NextActionPerformed
        // TODO add your handling code here:
        if(radListAll.isSelected())
        {
        lC.setVisible(false);
        lD.setVisible(false);
        locLab.setVisible(false);
        lN.setVisible(false);
        lS.setVisible(false);
        lC.setVisible(false);
        tname.setVisible(false);
        tLocation.setVisible(false);
        tDate.setVisible(false);
        tTime.setVisible(false);
        tContact.setVisible(false);
            btn_Search.setVisible(false);
            jScrollPane1.setVisible(true);
            Statement pstmt;
        pstmt = null;
       Connection conn=null;
       ResultSet rs = null;
         try{
             
             Class.forName("com.mysql.jdbc.Driver");
           conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/shop","root","stid");
           stmt=conn.createStatement();
           rs=stmt.executeQuery("select * from Customers;");
        empTable.setModel(DbUtils.resultSetToTableModel(rs));
}
catch(Exception ex){
JOptionPane.showMessageDialog(null, ex.getMessage());
}
finally{
    try{
        rs.close();
        pstmt.close();
         
    }
    catch(Exception ex){}}
        }
        
        else if(radSearch.isSelected()){
            jScrollPane1.setVisible(false);
            lN.setVisible(true);
            tname.setVisible(true);
            locLab.setVisible(true);
            tLocation.setVisible(true);
            btn_Search.setVisible(true);
        }
        
    }//GEN-LAST:event_btn_NextActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         tname.setText("");
        tLocation.setText("");
        tDate.setText("");
        tTime.setText("");
        tContact.setText("");
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Stark_Industries_DETAILS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Stark_Industries_DETAILS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Stark_Industries_DETAILS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Stark_Industries_DETAILS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Record_Details().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Next;
    private javax.swing.JButton btn_Search;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTable empTable;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lC;
    private javax.swing.JLabel lD;
    private javax.swing.JLabel lN;
    private javax.swing.JLabel lS;
    private javax.swing.JLabel locLab;
    private javax.swing.JRadioButton radListAll;
    private javax.swing.JRadioButton radSearch;
    public static javax.swing.JTextField tContact;
    public static javax.swing.JTextField tDate;
    private javax.swing.JTextField tLocation;
    public static javax.swing.JTextField tTime;
    public static transient volatile javax.swing.JTextField tname;
    // End of variables declaration//GEN-END:variables

    void Close() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
